# Generated by Django 4.0 on 2021-12-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctf_name', models.CharField(default='sCTF', max_length=60)),
                ('ctf_active', models.BooleanField(default=True)),
                ('uploaded_logo', models.BooleanField(default=False)),
                ('logo_link', models.CharField(default='', max_length=255)),
                ('uploaded_favicon', models.BooleanField(default=False)),
                ('favicon_link', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
