# Generated by Django 4.0 on 2021-12-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challs',
            name='flags',
            field=models.CharField(default='', max_length=255),
        ),
    ]
