# Generated by Django 4.0 on 2021-12-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challs', '0002_challs_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='challs',
            name='files',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='challs',
            name='static_value',
            field=models.BooleanField(default=False),
        ),
    ]
