# Generated by Django 4.0 on 2021-12-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challs', '0003_challs_files_challs_static_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='challs',
            name='time_created',
            field=models.CharField(default='JANUAR 2022', max_length=255),
        ),
    ]
