# Generated by Django 4.0 on 2021-12-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challs', '0004_challs_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='challs',
            name='casesens',
            field=models.BooleanField(default=True),
        ),
    ]
